version: '3.3'

services:
  cinder-pike-db:
    image: mariadb:10.4
    volumes:
      - "./database/:/docker-entrypoint-initdb.d" 
    environment:
      MYSQL_ROOT_PASSWORD: 123123Aa
      MYSQL_DATABASE: cinder 
      MYSQL_USER: cinder
      MYSQL_PASSWORD: 123123Aa 

  cinder-pike:
    depends_on:
      - cinder-pike-db
    build: .
    links:
      - cinder-pike-db:database
    volumes:
      - "./resultdb/:/root/results"
    command: bash -c "cinder-manage db sync && mysqldump -uroot -p123123Aa -hdatabase cinder> /root/results/cinder-pike.sql && tail -f /dev/null"
    
